- hosts: all
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/ssh_keys/root_rsa"
    ansible_user: "root" 
  gather_facts: False
  tasks:
    # ansible only requires only a minimal installation of python 2.x on the managed machines
    - name: "ansible required: install python"
      raw: apt update -y && apt install python-minimal -y && apt install python-simplejson -y

- hosts: all
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/ssh_keys/root_rsa"
    ansible_user: "root"
  tasks:
    - name: "set up bashrc for root user"
      copy:
        src: "{{ playbook_dir }}/roles/user-setup/files/.bashrc"
        dest: "/root/.bashrc"
        owner: "0"
        group: "0"
        mode: 0600

    - name: "ensure /data/backup exists"
      file:
        path: /data/backup
        mode: 0700
        owner: "root"
        group: "root"
        state: directory

    - name: "ensure /data/backup/teamspeak3 exists"
      file:
        path: /data/backup/teamspeak3
        mode: 0700
        owner: "root"
        group: "root"
        state: directory

- hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/ssh_keys/root_rsa"
    ansible_user: "root"
    
    apt_update_cache: True
    apt_restart_after_dist_upgrade: True
  roles:
    - role: essential-software-setup