---
- hosts: teamspeak3
  become: true
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/ssh_keys/root_rsa"
    ansible_user: "root"
    
  roles:
    - geerlingguy.docker
    - docker-post-setup
    - teamspeak3